Cargar datos

In [10]:
import pandas as pd

df = pd.read_csv('../data/raw/candidates.csv', sep=';')
df.head()

,First Name,Last Name,Email,Application Date,Country,YOE,Seniority,Technology,Code Challenge Score,Technical Interview Score
0,Bernadette,Langworth,leonard91@yahoo.com,2021-02-26,Norway,2,Intern,Data Engineer,3,3
1,Camryn,Reynolds,zelda56@hotmail.com,2021-09-09,Panama,10,Intern,Data Engineer,2,10
2,Larue,Spinka,okey_schultz41@gmail.com,2020-04-14,Belarus,4,Mid-Level,Client Success,10,9
3,Arch,Spinka,elvera_kulas@yahoo.com,2020-10-01,Eritrea,25,Trainee,QA Manual,7,1
4,Larue,Altenwerth,minnie.gislason@gmail.com,2020-05-20,Myanmar,13,Mid-Level,Social Media Community Management,9,7

Fecha minima y Fecha maxima

In [16]:
print(df['Application Date'].min())
print(df['Application Date'].max())

2018-01-01
2022-07-04

Tamaño y tipos de datos

In [11]:
print(df.shape)      
print(df.dtypes)

(50000, 10)
First Name                     str
Last Name                      str
Email                          str
Application Date               str
Country                        str
YOE                          int64
Seniority                      str
Technology                     str
Code Challenge Score         int64
Technical Interview Score    int64
dtype: object

Valores faltantes

In [12]:
df.isnull().sum()

First Name                   0
Last Name                    0
Email                        0
Application Date             0
Country                      0
YOE                          0
Seniority                    0
Technology                   0
Code Challenge Score         0
Technical Interview Score    0
dtype: int64

Duplicados

In [13]:
df.duplicated().sum()

np.int64(0)

Columnas Categoricas

In [14]:
print(df['Country'].unique())
print(df['Seniority'].unique())
print(df['Technology'].unique())

<StringArray>
[               'Norway',                'Panama',               'Belarus',
               'Eritrea',               'Myanmar',              'Zimbabwe',
     'Wallis and Futuna',                 'Italy',           'Timor-Leste',
               'Armenia',
 ...
               'Georgia',           'Switzerland',              'Suriname',
               'Hungary',                 'Gabon', 'Sao Tome and Principe',
               'Mayotte',                 'Benin',                'Uganda',
               'Romania']
Length: 244, dtype: str
<StringArray>
['Intern', 'Mid-Level', 'Trainee', 'Junior', 'Lead', 'Architect', 'Senior']
Length: 7, dtype: str
<StringArray>
[                          'Data Engineer',
                          'Client Success',
                               'QA Manual',
       'Social Media Community Management',
                'Adobe Experience Manager',
                                   'Sales',
                                'Mulesoft',
                                  'DevOps',
               'Development - CMS Backend',
                              'Salesforce',
                   'System Administration',
                                'Security',
                        'Game Development',
              'Development - CMS Frontend',
                     'Security Compliance',
                   'Development - Backend',
                                  'Design',
 'Business Analytics / Project Management',
                  'Development - Frontend',
                 'Development - FullStack',
                   'Business Intelligence',
                 'Database Administration',
                           'QA Automation',
                       'Technical Writing']
Length: 24, dtype: str

Estadisticas de los puntajes

In [15]:
df[['Code Challenge Score', 'Technical Interview Score', 'YOE']].describe()

       Code Challenge Score  Technical Interview Score           YOE
count          50000.000000               50000.000000  50000.000000
mean               4.996400                   5.003880     15.286980
std                3.166896                   3.165082      8.830652
min                0.000000                   0.000000      0.000000
25%                2.000000                   2.000000      8.000000
50%                5.000000                   5.000000     15.000000
75%                8.000000                   8.000000     23.000000
max               10.000000                  10.000000     30.000000